---
title: "Actividad2_A01177261"
output: html_document
---

# Librerias


```{r}

library(stats)
library( psych )
library(readxl)
library(MASS)
library(ISLR)
library(fRegression)
library(vcd)

```

```{r}
base <- read_xls("C:/Users/aalma/OneDrive/TEC/Carrera/5to semestre/3er Parcial/Modelación y programación financiera (Gpo 3)/Actividades/Actividad 2/default of credit card clients.xls")
```


# Modelo LOGIT




```{r}
modelo_Logit<-glm(base$`default payment next month`~.  , data =base , family = binomial(link = "logit"))

summary(modelo_Logit)

```


```{r}
modelo_Probit<-glm(base$`default payment next month`~.  , data =base , family = binomial(link = "probit"))

summary(modelo_Probit)
```


Estimamos los criterios de información para cada modelo


```{r}
CIA_Logit=AIC(modelo_Logit)
CIA_Probit=AIC(modelo_Probit)
CIA_Logit
CIA_Probit

```


El modelo con mejor ajuste en base al CIA es el lobit
#Es el que mas se ajusta porque tiene menos errores

